### ISSUE TITLE
Note: We Are Magnetic has closed. 

### ISSUE THREAD

**Issue by EdwardDeaver** [j0hnm4r5/awesome-creative-technology#1]
First I want to say I love this list thank you for it!

Second, We Are Magnetic closed down in August. 

https://www.adweek.com/agencies/experiential-agency-were-magnetic-closing-covid-19/

[I'm not associated with We Are Magnetic]

**Comment by j0hnm4r5** [comment]
Thanks! I moved to to a new "closed" section in 87b2ff9de99feae52801aeaa0bdfcaa597278f79. Their website is down now, but hopefully people can still search for their stuff as reference.
