### ISSUE TITLE
Add Study Field of Creative Technology

### ISSUE THREAD

**Issue by SuiOni** [j0hnm4r5/awesome-creative-technology#33]
Hey there,
awesome list!
How about adding where and what to study to get into all creative and technology?

Like the Interactive Telecommunications Program NYT Tisch or
some other New Media / Interactive Design / Creative Tech studies which are popping out everywhere.

I could add quite some entries if thats something of value.

Whatcha think?
Best
Sak

**Comment by j0hnm4r5** [comment]
We just added a section for that! Great idea. Feel free to add some more programs if you have time.
