### ISSUE TITLE
node_modules committed to repo

### ISSUE THREAD

**Issue by JohnENoonan** [j0hnm4r5/awesome-creative-technology#68]
Hey @j0hnm4r5, I'm merging this root repository into my fork and I noticed that the `node_modules` folder has been committed to the repo. Was this done on purpose? If so I can merge it in, I just wanted to make sure since it seems like it was most recently committed by the github action.

**Comment by j0hnm4r5** [comment]
Definitely not on purpose; I must have missed it after the last commit

**Comment by JohnENoonan** [comment]
I believe I have addressed this in #69
